# Generated by Django 3.2.5 on 2021-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_inventorylist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='item',
            name='date_purchased',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='where_purchased',
            field=models.CharField(choices=[('AM', 'Amazon'), ('BB', 'Best Buy'), ('TA', 'Target'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
